### PR TITLE
Fix the Print widget french language translations

### LINKED ISSUE #818: Error Print Widget with 'locale=fr'
https://demo.cmv.io/viewer/?locale=fr 
Click on Print widget not open the widget

__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
https://demo.cmv.io/viewer/?locale=fr 
Click on Print widget not open the widget

With all other locale langage, the "printer widget" works fine

__Steps to reproduce:__

just : https://demo.cmv.io/viewer/?locale=fr 
and Click on Print widget

__Expected results:__

__Actual results:__

__Environment:__

Firefox quantum on lubuntu
Firefox on windows 8.0

### PR DESCRIPTION
**Pull request by tmcgee**
fixes #818

### CODE REVIEW

**Comment by amcgee** [comment]
Looks good to me, but I extended the fix to the other French phrases with apostrophes (and one rogue back-tick).  Feel free to review and merge if it looks good.  @tmcgee

**Comment by tmcgee** [comment]
@amcgee I looked at that originally. If I recall correctly from back then, changing the additional phrases didn't have the desired affect and resulted in the the second `\` being displayed within the U.I.

**Comment by amcgee** [comment]
Huh.  OK, I'll revert those changes.

**Comment by amcgee** [comment]
Might be worth looking into why they're treated differently at some point.

**Comment by tmcgee** [comment]
IIRC, the difference is a dojo inconsistency how/where the nls translation is used in the main Print form versus the Print Settings DropDown Button.

File: viewer/js/gis/dijit/Print/nls/fr/resource.js [hunk 1]
```diff
@@ -17,8 +17,8 @@ define ({
     printQualityOptions: 'Qualité d`impression',
```
Comment (amcgee) [inline viewer/js/gis/dijit/Print/nls/fr/resource.js]: What about this use of a back-tick instead of an apostrophe?  Seems like it may have been added as a work-around for the issue we're fixing in other translation keys?

Comment (amcgee) [reply viewer/js/gis/dijit/Print/nls/fr/resource.js]: @tmcgee

**Comment by tmcgee** [comment]
@amcgee I verified my original recollection regarding the additional `\\` characters. That results in the `\` appearing in the U.I.

I did replace the rogue back-tick/accent character with an apostrophe as you noted in your original comment.

**Review by amcgee — APPROVED** [review]
Assuming the printQualityOptions string is of the class that doesn't need an escaped backslash, this looks good!

File: viewer/js/gis/dijit/Print/nls/fr/resource.js (hunk 1 above)
Comment (tmcgee) [reply viewer/js/gis/dijit/Print/nls/fr/resource.js]: I changed that in https://github.com/cmv/cmv-app/pull/826/commits/be8af9eb238850b3a8fc1ce21601d1d97e3d6088

Comment (amcgee) [reply viewer/js/gis/dijit/Print/nls/fr/resource.js]: Ah sorry I thought I marked this review as complete, apparently it just submitted the comments I made a while back.
